linters:
  disable-all: true # We do this to own which linters we want to enable.
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asciicheck
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - gosec
    - exhaustive
    - gofumpt
    - goimports
    - makezero
    - nakedret
    - nosprintfhostport
    - prealloc
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - tenv
    - tparallel
    - unparam
    - usestdlibvars
    - wastedassign
    - gci
linters-settings:
  errorlint:
    errorf: true
  makezero:
    always: true
  gci:
    sections:
      - standard
      - prefix(github.com/kevinrobayna)
      - prefix(github.com/kevinrobayna/aoc2md)
      - default
  gofumpt:
    module-path: github.com/kevinrobayna/aoc2md
    extra-rules: true

